### ISSUE TITLE
Is microscope camera too light-sensitive ?

### ISSUE THREAD

**Issue by Frdeporte** [bhowiebkr/laser-level-webcam#16]
Hi ,

In first, I have tried your software with 2,9mm sensor width but the width was not enough regarding to my beams deviation.
So, I’ve bought the following microscope webcam with larger sensor width.

https://www.bresser.de/fr/Astronomie/Accessoires/Astrophotographie/BRESSER-Camera-oculaire-MikrOkular-Full-HD.html

The pixel are 3mm width instead of 1,4mm.
In this way I’ve a larger sensor width of 5.86mm.

Now, I obtain the followinf results :
 
![mikrocular](https://github.com/bhowiebkr/laser-level-webcam/assets/143429731/7d7dd26e-b4a6-49a8-b4e9-8dea343b1148)

All the sensor feed window is fitted by the laser line, is this new camera too light-sensitive ?

Thanks a lot.

Fred

**Comment by bhowiebkr** [comment]
That microscope camera sensor looks like it should work well for this purpose. The laser diode you are using is probably outputting too much light. I’d suggest getting one of these DC - DC converters. They allow you adjust the voltage and/or the current to the load (laser) I’m using one (not this particular one) to bring down the voltage to the diode. You’ll want to adjust the laser intensity so that the sensor shows a nice hump where the middle of the beam is. You don’t want the image sensor to be clipping the bright/white pixels. 

https://www.amazon.ca/JZK-Adjustable-Converter-1-25-36V-Regulator/dp/B09TT1Q739

Also for good results in the “Device Settings” button turn off stuff like auto exposure or other automatic things, filters, etc. All camera’s are different and will show different parameters. In order for that button to work you’ll need to have FFMPEG installed and part of your path (in windows going to the command shell you should be able to type in ffmpeg and see the output of it. It shouldn’t say anything about not finding it)
